### ISSUE TITLE
ANOTHER user story

### ISSUE THREAD

**Issue by GetanehT** [GetanehT/My-second-agile#3]
In order to **do my job** as a **user**, I can **fill the form**

#Acceptance Criteria
- **Acceptance Criteria 1:** There must be 300 character input box for a feedback 
* **Acceptance Criteria 2:** After submitting the feedback submission confirmation should be adjusted. 
+ **Acceptance Criteria 3:** The option should appear next submit button
# Tasks
- [x] Task 1. Update a feedback submission form
- [ ] Task 2. Create HTML, CSS, and JS
- [ ] Task 3. Create code
- [ ] Task 4. Test the completed functionality
